name: readme-activity
run-name: Update README.md with Recent Activity
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  generate-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     # - uses: Rafi98/GH_TASK2@main
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        with:
          COMMIT_MSG: "docs(README): auto-update activity [skip ci]"
          #file_path: .github/workflows/topics.yml
          MAX_LINES: 10
