#name: readme-activity
#run-name: Update README.md with Recent Activity
#on:
  #schedule:
    #- cron: "0 * * * *" #Runs every hour
  #workflow_dispatch:
#jobs:
  #generate-activity:
    #runs-on: ubuntu-latest
    
    #steps:
      #- name: Checkout Repository
        #uses: actions/checkout@v2

      #- name: Update README Activity
        #uses: jamesgeorge007/github-activity-readme@master
        
      ##- uses: actions/checkout@v2
      ##- uses: Rafi98/GH_TASK2@main
        #env:
          #ACTIONS_STEP_DEBUG: true
          #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #with:
          #COMMIT_MSG: "docs(README): auto-update activity [skip ci]"
          #MAX_LINES: 10
